stages:
  - build
  - test
  - scan
  - push

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/frontend"
  IMAGE_FULL: "$IMAGE_NAME:$IMAGE_TAG"

services:
  - docker:dind

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin

build:
  stage: build
  script:
    - echo "Building frontend image..."
    - docker build -t $IMAGE_FULL .
  only:
    - branches

test:
  stage: test
  script:
    - echo "Running tests for frontend..."
    - docker run --rm -e NODE_ENV=test $IMAGE_FULL npm run test
  only:
    - branches

scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - echo "Scanning frontend image for vulnerabilities..."
    - trivy image --exit-code 1 --severity HIGH,CRITICAL --no-progress $IMAGE_FULL
  only:
    - branches

push:
  stage: push
  script:
    - echo "Pushing frontend image..."
    - docker push $IMAGE_FULL
  only:
    - branches
