stages:
  - build
  - test
  - scan
  - push

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/order-service"
  IMAGE_FULL: "$IMAGE_NAME:$IMAGE_TAG"

services:
  - docker:dind

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE_FULL .
  only:
    - branches

test:
  stage: test
  script:
    - docker run --rm -v $CI_PROJECT_DIR/services/order-service:/usr/src/app -w /usr/src/app node:16-alpine sh -c "npm install && npm run test"
  only:
    - branches

scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - trivy image --exit-code 1 --severity HIGH,CRITICAL --no-progress $IMAGE_FULL
  only:
    - branches

push:
  stage: push
  script:
    - docker push $IMAGE_FULL
  only:
    - branches
