name: CI Test Pipeline for All Services

on:
  push:
    branches:
      - main

jobs:
  auth:
    name: Auth Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Auth Service
        run: |
          cd services/auth-service
          npm install
          npm test

  order:
    name: Order Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Order Service
        run: |
          cd services/order-service
          npm install
          npm test

  product:
    name: Product Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Product Service
        run: |
          cd services/product-service
          npm install
          npm test

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Frontend
        run: |
          cd frontend
          npm install
          npm test